//
//  Feedback.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Feedback: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _planId: String?
    var _id: String?
    var _created: NSNumber?
    var _goal1Feedback: String?
    var _goal2Feedback: String?
    var _goal3Feedback: String?
    var _modified: NSNumber?
    var _teacher: String?
    var _userId: String?
    
    class func dynamoDBTableName() -> String {

        return "iosnotesapp-mobilehub-2027009978-feedback"
    }
    
    class func hashKeyAttribute() -> String {

        return "_planId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_planId" : "planId",
               "_id" : "id",
               "_created" : "created",
               "_goal1Feedback" : "goal1Feedback",
               "_goal2Feedback" : "goal2Feedback",
               "_goal3Feedback" : "goal3Feedback",
               "_modified" : "modified",
               "_teacher" : "teacher",
               "_userId" : "userId",
        ]
    }
}
